@host = http://localhost:5215

###
GET {{host}}/ping

###
# @name CreateSession
POST {{host}}/chat/complete

###
POST {{host}}/chat/complete/{{CreateSession.response.body.session_id}}
Content-Type: application/json

{
  "message": "I am interested in C#. Which session should I attend at BASTA?"
}
